apiVersion: infrastructure.ccs.vmware.com/v1alpha1
kind: SupervisorNamespaceClassConfig
metadata:
  name: ${SV_NAMESPACE_CLASS}
spec:
  storageClasses:
    - name: ${STORAGE_CLASS}
  vmClasses:
    - name: "*"
  contentSources:
    - name: "*"
      type: ContentLibrary
  # Below limits are an EXAMPLE! Setting them may cause unexpected behavior in your namespace
  # Either set reasonable limits, or remove the below section to get unlimited resources
 #limits:
 #  - name: cpu_limit
 #    limit: "1000" # This value is in Mhz
 #  - name: cpu_limit_default
 #    limit: "800" # This value is in Mhz
 #  - name: pod_count
 #    limit: "((parameters.pods))"
  supervisorSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - ${ENVIRONMENT}
