
apiVersion: infrastructure.ccs.vmware.com/v1alpha1
kind: SupervisorNamespaceClassBinding
metadata:
  name: ${SV_NAMESPACE_CLASS}
  namespace: ${PROJECT}
spec:
  overrideParameters:
    - name: pods
      type: Integer
      const: 50
