apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
  labels:
    tkgs-cluster-selector: tkc-1
spec:
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
          - 192.168.156.0/20
      services:
        cidrBlocks:
          - 10.96.0.0/12
      serviceDomain: cluster.local
    storage:
      classes:
        - tmm-kubernetes-storage-policy
      defaultClass: tmm-kubernetes-storage-policy   #Default PVC storage class
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: tmm-kubernetes-storage-policy                
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
    nodePools:
      - name: tkc-1-nodepool-qzyl
        replicas: 1
        vmClass: best-effort-small
        storageClass: tmm-kubernetes-storage-policy
        tkr:
          reference:
            name: v1.23.8---vmware.3-tkg.1