apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
  labels:
    tkgs-cluster-selector: tkc-1
spec:
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
          - 192.168.156.0/20
      services:
        cidrBlocks:
          - 10.96.0.0/12
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: explore-kubernetes-storage-policy
      defaultClass: explore-kubernetes-storage-policy                  #Default PVC storage class
      tkr:
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
    nodePools:
      - name: tkgs-cluster-nodepool-qzyl
        replicas: 1
        vmClass: best-effort-small
        storageClass: explore-kubernetes-storage-policy
        tkr:
          reference:
            name: v1.22.9---vmware.1-tkg.1.cc71bc8

